### ISSUE TITLE
Stopping music by pressing button casues error for about 10 mins after

### ISSUE THREAD

**Issue by gingerling** [forslund/spotify-skill#56] opened 2018-09-22 18:14 UTC
Hi, I don't have any error logs for this as I am new to Mycroft however I find that if I successfully play a song and decide to stop it (not sure how I am supposed to do that) I press the button on Mark 1 and he stops, but then for about 10 mins after if I try and do anything else with Spotify he says an error has occurred. I can try and work with you to get more info, but maybe this is easy to reproduce?

**Comment by gingerling** [comment] 2018-09-22 19:03
The only thing that seems to make the error stop is search spotify for xyz - weird.

**Comment by forslund** [comment] 2018-09-22 19:11
Thanks for reporting.  I'll see if I can reproduce. What was the utterance you used? (There are a couple of different handlers depending on the utterance so an examle might be useful)

**Comment by gingerling** [comment] 2018-09-22 20:34
I think: Hey Mycroft, play me some radiohead

Hey Mycroft, search spotify for radiohead sometimes fixes it (it works and then the other error seems to be resolved).

**Comment by forslund** [comment] 2018-09-27 04:38
Hi again, I've tried to reproduce but haven't been able to yet. If it occurs and you're able to get the log what would be very helpful.

**Comment by forslund** [comment] 2019-06-13 06:40
Hi, since there's been no communication on this for a couple of months I'm closing it. If you still are having problems with this feel free to re-open.

**Closed as completed by forslund** 2019-06-13 06:40 UTC
